# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Java Configuration - Remove or comment out the specific java.home
# org.gradle.java.home=C:\Program Files\Java\jdk-21

# Enable toolchain auto-detection and auto-download
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19

# Mod Properties
mod_version=26.2
maven_group=com.nohiddenadvancements
archives_base_name=why-stack-of-16

# Dependencies
fabric_version=0.158.0+26.2

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.12-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists